#yml文件中冒号后面和值中间有个空格，这个空格不能省略
#注意如果属性是 lastName  yml中提示你的属性是last-name,这两者在yml中是等价的，都可以用
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: sat

---
server:
  port: 8084
spring:
  profiles: prod